name=BD37033
version=1.0.0
author=Kirill Primus <primus180@mail.ru>
maintainer=Kirill Primus <primus180@mail.ru>
sentence=Библиотека для управления аудиопроцессором BD37033FV-M
paragraph=Поддерживает громкость, тембры (Bass/Middle/Treble), баланс, Loudness, управление входами, сабвуфером и микшером.
category=Audio
url=https://github.com/PrimusKirill/BD37033
architectures=esp32,avr
